### ISSUE TITLE
Ansible

### ISSUE THREAD

**Issue by emanpatricio** [geerlingguy/packer-ubuntu-1804#11]
This is more of a question actually.

I added this in main.yml

    - name: Copy file to a remote server
      copy:
        src: ~/text.txt
        dest: /tmp

hoping to copy the text.txt in my local(mac) to guest(provision machine)

but Im getting this error
    virtualbox-iso:
    virtualbox-iso: TASK [Copy file to a remote server] ********************************************
    virtualbox-iso: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
    virtualbox-iso: fatal: [127.0.0.1]: FAILED! => **{"changed": false, "msg": "Could not find or access '~/text.txt' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}**

I did also tried addint remote_src: yes but its not working.

Any idea?

**Comment by dovry** [comment]
You don't use Ansible on the localhost (packer image) to move files between hosts.
You use the [File provisioner](https://www.packer.io/docs/provisioners/file.html)

**Comment by geerlingguy** [comment]
This project is deprecated as things are being consolidated into https://github.com/geerlingguy/packer-boxes; see issue: https://github.com/geerlingguy/packer-boxes/issues/45
