### ISSUE TITLE
Installing U16, not U18

### ISSUE THREAD

**Issue by m-denton** [geerlingguy/packer-ubuntu-1804#2]
"iso_url": "http://cdimage.ubuntu.com/ubuntu/releases/bionic/release/ubuntu-18.04-server-amd64.iso",

Have this set for my iso. Seems to be installing U16.04 still. 

`root@ubuntu:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial`

**Comment by geerlingguy** [comment]
It seems to be building 18.04 for me, with http://cdimage.ubuntu.com/ubuntu/releases/bionic/release/ubuntu-18.04-server-amd64.iso :/

Maybe somehow 16.04 is cached locally? Can you delete the cache directory and try again?
