### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by jmcgeheeiv** [geerlingguy/packer-ubuntu-1804#5]
Thank you for the nice example.
It would be nice if you could add an explicit `LICENSE.txt` file to compliment your MIT license statement in `README.md`.

**Comment by geerlingguy** [comment]
This project is deprecated as things are being consolidated into https://github.com/geerlingguy/packer-boxes; see issue: https://github.com/geerlingguy/packer-boxes/issues/45
