### ISSUE TITLE
Can't get past the "Confirm Destructive action" popup

### ISSUE THREAD

**Issue by szalishchuk** [geerlingguy/packer-ubuntu-1804#7]
Hey Jeff,

I've been playing for hours with my setup using your config as a reference, but even with pure clone of this repo, I can't get past the partitioning step, where packer can't get past the "Confirm Destructive action" popup. If I intervene manually and select "Continue", then fill out the user credentials on the next step, packer picks it up, successfully provisions the vm and then exports it into the box. I have tried this on Arch Linux and Mac ending up having the same result.

Given that 16.04 works fine with the same preseed.cfg, I assume that there's a missing step in the boot_commands sequence which is supposed to take care of the popup, but can't pin point where exactly.

**Comment by ehtobsemaj** [comment]
Any solution?  stuck here too..

**Comment by gh-lbaldwin** [comment]
I spent more than an acceptable amount of time trying everything.  I thankfully came across someone mentioning, apologies can't find source link, the following:

Ubuntu 18.04.1 the bootcommand " noapic<wait>" must be removed

If you have any problems, lmk.  I have a working template.

**Comment by ehtobsemaj** [comment]
> If you have any problems, lmk. I have a working template.

Thanks, just tried with "noapic" removed.  Same issue, stuck at "Confirm destructive action" popup on the Filesystem setup screen when viewing the VM console.

**Comment by gh-lbaldwin** [comment]
errrr apologies.  my noted fix was related to the 18.04.1 kernel apic_update_vector crash when using packer to provision on a vmware 6.5 host.

please see the following example preseed
https://gist.github.com/guberno/927bf92709b113399782319ba62344a4

**Comment by akunaatrium** [comment]
Which ISO exactly are you using? Make sure you are not using the "Live" version of the ISO.

**Comment by qmatmol** [comment]
I can confirm having similar issues with Live installs. 

Preseeding the Ubuntu install works for:

ubuntu-18.04-server-amd64.iso
ubuntu-18.04.1-server-amd64.iso

Preseeding the Ubuntu install does not work for:

ubuntu-18.04.1.0-live-server-amd64.iso
ubuntu-18.04.2-live-server-amd64.iso
ubuntu-18.10-live-server-amd64.iso

Obviously, the problem happens when using Live CDs. 

I have tried most options for preseeding I could find, but no success. I cannot get past the "Confirm Destructive action" popup. Seems like the only way is to use non-live installs.

My Packer version: 1.3.4, 1.3.5
My Vagrant version: 2.2.3, 2.2.4
My VirtualBox version: 6.0.4
My host platform: Windows 10

**Comment by estenrye** [comment]
If you are looking for the non-live cd 18.04.2 images, they can be found here:
http://cdimage.ubuntu.com/releases/18.04/release/

http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.2-server-amd64.iso

**Comment by qmatmol** [comment]
Thanks!

**Comment by RichardRanft** [comment]
I'm having this same issue.
here's my preseed partitioning section:
`d-i partman-auto/disk string /dev/sda
d-i partman-auto/method string regular
d-i partman/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true
`
The result is that the "Confirm Destructive Action" popup is shown, is dismissed, is shown again, is dismissed again, is shown yet again, then after it is dismissed the command prompt output displays "Waiting for SSH to become available...", then it sits there until the "ssh_wait_timeout" expires.
[ubuntu-18.json.txt](https://github.com/geerlingguy/packer-ubuntu-1804/files/3838554/ubuntu-18.json.txt)
[preseed.cfg.txt](https://github.com/geerlingguy/packer-ubuntu-1804/files/3838555/preseed.cfg.txt)

**Comment by geerlingguy** [comment]
This project is deprecated as things are being consolidated into https://github.com/geerlingguy/packer-boxes; see issue: https://github.com/geerlingguy/packer-boxes/issues/45
