### ISSUE TITLE
minimal ubuntu

### ISSUE THREAD

**Issue by 030** [geerlingguy/packer-ubuntu-1804#8]
Could you indicate whether this uses Ubuntu minimal? I have checked the packer.json and I think it is the normal one. Is that correct? Is there a repository that uses the minimal Ubuntu? Is there something I can do?

**Comment by geerlingguy** [comment]
This project is deprecated as things are being consolidated into https://github.com/geerlingguy/packer-boxes; see issue: https://github.com/geerlingguy/packer-boxes/issues/45
